zookeeper:
  image: samsara/zookeeper
  container_name: zookeeper
  ports:
    - "2181:2181"
    - "15001:15000"
  environment:
    ZK_SERVER_ID: 1
  volumes:
    - /tmp/docker/zk1/logs:/logs
    - /tmp/docker/zk1/data:/data

kafka1:
  image: samsara/kafka
  container_name: kafka1
  ports:
    - "9092:9092"
    - "15002:15000"
  links:
    - zookeeper
  environment:
    KAFKA_BROKER_ID: 1
    KAFKA_OFFSETS_STORAGE: kafka
  volumes:
    - /tmp/docker/kafka1/logs:/logs
    - /tmp/docker/kafka1/data:/data

kafka2:
  image: samsara/kafka
  container_name: kafka2
  ports:
    - "9093:9093"
    - "15003:15000"
  links:
    - zookeeper
  environment:
    KAFKA_BROKER_ID: 2
    KAFKA_BROKER_PORT: 9093
    KAFKA_OFFSETS_STORAGE: kafka
  volumes:
    - /tmp/docker/kafka2/logs:/logs
    - /tmp/docker/kafka2/data:/data

kafka3:
  image: samsara/kafka
  container_name: kafka3
  ports:
    - "9094:9094"
    - "15004:15000"
  links:
    - zookeeper
  environment:
    KAFKA_BROKER_ID: 3
    KAFKA_BROKER_PORT: 9094
    KAFKA_OFFSETS_STORAGE: kafka
  volumes:
    - /tmp/docker/kafka3/logs:/logs
    - /tmp/docker/kafka3/data:/data

schemaregistry:
  build: schema-registry
  container_name: schemaregistry
  environment:
    SCHEMA_REGISTRY_DEBUG: "true"
  ports:
    - "8081:8081"
  links:
    - zookeeper
    - kafka1
    - kafka2
    - kafka3

kafkarestproxy:
  build: kafka-rest-proxy
  container_name: kafkarestproxy
  ports:
    - "8082:8082"
  links:
    - zookeeper
    - schemaregistry

riemann:
  build: /Users/sjohnson/projects/panopticon
  container_name: riemann
  links:
    - riemann-dash
  ports:
    - "5555:5555"
    - "5556:5556"

riemann-dash:
  build: /Users/sjohnson/projects/panopticon
  container_name: riemann-dash
  entrypoint:
    - /panopticon/deploy/bin/run
    - run-dash
  ports:
    - "4567:4567"